apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Q63x87udyhI=,iv:wqESkpTXpPRtO8mjSJmmKVXd5o2dBgPWdtNW4ta+/fY=,tag:HlxwbbBypSncD22ehoCwug==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ0VkOVh2cGtTeGloWUNT
            b0hmQ2t1WjVBWkh4Z0pWNDkvZTdaYW5Ga1FBCkZlMlplR3dpazV0Yk1HekMyam15
            Z2lwd3lVZzQrUHIyeEQvbkxHWkpYM2cKLS0tIExtbVFENzFmQ0lCNVBYd0RTWFZp
            dGJoL2YyN3ZrRTBwU0pqUTZ2MDU2UW8KXdoQVwFT/S86ShwihnGuDdkn11/5zbQj
            hTfRsJJ9I2Oeu2fFkzRueDv33woexR09AQRj8Z9D77fFOrw8vmVQ6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T15:03:12Z"
    mac: ENC[AES256_GCM,data:YurfIaGW4KGolKPlFtgr4zxHxkOSmLg/6kTBPgGcCGvBEXkNPhK8glAI6O4dPdPFJAjxQLIXg1HEQwzUaFQ4aE0+J59SNw/LTyg7aDN6x21WgDfNNgxjJdWNldbEA9MoRye0n8z/kxXN0FxP9rZ+u1H1T9mn/UyU8lnTfz9s6zQ=,iv:lDcXi7sdWz43ZEBM+XlWYZSgU00qMGo0eopsb30uCzc=,tag:CBZSqXGawAXSU+eRxIx+cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
