apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: linkding
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    - hostname: linkding.quickyrails.com
      service: http://linkding.linkding.svc.cluster.local:9090
    - hostname: ghostfolio.quickyrails.com
      service: http://ghostfolio.ghostfolio.svc.cluster.local:3333
    - hostname: grafana.quickyrails.com
      service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
    - service: http_status:404

