apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel
resources:
  - ../../base/cloudflare-tunnel
  - configmap.yaml
  - cloudflare-secrets.yaml
  - tunnel-secrets.yaml

