apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghostfolio
  template:
    metadata:
      labels:
        app: ghostfolio
    spec:
      containers:
        - name: ghostfolio
          image: ghostfolio/ghostfolio:2.231.0
          ports:
            - containerPort: 3333
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: database-url
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: redis-port
            - name: ACCESS_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: access-token-salt
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: jwt-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio
spec:
  ports:
    - port: 3333
  selector:
    app: ghostfolio
